language: java

jdk: openjdk11

branches:
  only:
  - master

addons:
  ssh_known_hosts:
  - 172.104.134.26

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_install:
- openssl aes-256-cbc -K $encrypted_8e85193f3435_key -iv $encrypted_8e85193f3435_iv
  -in scripts/linode-deploy.enc -out scripts/linode-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/linode-deploy ~/.ssh/linode-deploy
- chmod 600 ~/.ssh/linode-deploy
- ssh-add ~/.ssh/linode-deploy
- echo -e "Host 172.104.134.26\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod +x gradlew

install: "./gradlew app:assemble"

script: "./gradlew app:check"

before_deploy:
- chmod +x scripts/deploy.sh

deploy:
- provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master